stages:
    - build
    - deploy

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

build:
    stage: build
    retry: 2
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    tags:
        - linux
        - worker
        - shell

deploy:
    stage: deploy
    environment:
        name: production
        url: https://apps.caseyWebb.xyz/dcp-badger
    tags:
        - eris
        - shell
    script:
        - (docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME) || true
        - docker run --detach --name $CONTAINER_NAME --publish $HOST_PORT:3000 --restart unless-stopped $IMAGE_TAG
    only:
        - master@caseyWebb/dcp-badger
    variables:
        HOST_PORT: 9000
        CONTAINER_NAME: dcp-badger-prod